### ISSUE TITLE
Rancher 2.0 Beta compatiblity

### ISSUE THREAD

**Issue by cipherspec** [tozny/rancher-lets-encrypt#31]
Is rancher-lets-encrypt compatible to rancher 2.0 beta yet?

I'm not sure if I should test this out. Propably, I will kill my productive environment...

**Comment by ericmann** [comment]
We haven't tested with the beta, but I'll add that to our to-do list.

If you want to test it out somewhere _other_ than in production, please do. Just be sure to let us know.

If you're running a beta in production, though, I'd expect something somewhere would break, and not necessarily with this tool. Just be super careful running anything other than a stable release in a production environment.

**Comment by RamonSmit** [comment]
Is there any update on this? I can't get this to work on my setup.

**Comment by fernviridian** [comment]
@RamonSmit Please note that this tool was originally written for Rancher's 1.X releases, specifically their V1 api version. We have not changed the tool in a while since it has worked for us with versions from v1.1.X to v1.6.X. 

Even as Rancher 2.0 was release GA a short while ago, Tozny has no plans to adopt it currently, therefore adding support for this Rancher version is not on our roadmap. Rancher 2.0 is a total rewrite of Rancher, and this service heavily depends on using the Cattle orchestrator, which has been removed in Rancher 2.0 in favor of kubernetes. 

As rancher-lets-encrypt is an open-source tool, you are welcome to fork the repository and we would welcome a pull-request with this compatibility added, but I suspect the difference between 1.X and 2.X versions would make it easier to maintain two separate versions of the tooling.
